### ISSUE TITLE
Idea New Feature : Audio input

### ISSUE THREAD

**Issue by EliottJVN** [nils010485/autocorrect#1]
Salut Nils,

Ton appli est top j'adore !! 

J'ai clone ton répo pour bidouiller un peu car j'aimerais bien rajouter une fonctionnalité de transcription d'audio. C'est à dire pouvoir drag&drop un fichier audio d'un discours ou d'une interview et qu'on puisse récupérer le fichier retranscrit le plus fidèlement possible sans faute, dans la langue qu'on veut etc. En faite au lieu de passer un texte en entrée pouvoir passer un audio à ton application.

Sur mon temps libre, il y a une semaine j'avais codé une classe python qui prend en entrée un fichier audio (wav), l'IA fait sa magie (modèle Vosk pré entraîné qui tourne en local) et retourne le texte brute détecté (pas de ponctuation des fautes etc). Rien de bien incroyable, surtout codé avec Chat GPT donc bof bof... Mais je pense qu'il y a du potentiel. L'idée serait d'implémenter cette classe et de corriger la sortie et de pouvoir ensuite appliqué tes fonctionnalités dans l'application T'en penses quoi ?

Je connais seulement Python du coup si t'as des conseils sur ce que je peux modifier pour pouvoir implémenter ça rapidement ?

    Class Audio_to_Text ():

        def __init__ (self, audio_file:str, lst_model:str, ouput_file:str=None) -> None:
            self.audio_file = audio_file
            self.text_file = ouput_file
            self.lst_model = lst_model
            self.text = None
        
        def is_good_format(self, file):
            if file.getnchannels() != 1 or file.getsampwidth() != 2 or file.getframerate() not in [8000, 16000, 32000]:
                    raise ValueError("Le fichier audio doit être en mono PCM avec un taux d'échantillonnage de 8k, 16k ou 32k Hz.")
        
        def save_text(self):
            if self.text_file is None:
                # CREATE DEFAULT PATH HERE
                pass 
            if self.text is None:
                raise ValueError("Nothing to save")
            with open(self.text_file, "w", encoding="utf-8") as file:
                file.write(self.text)
        
        def audio_to_text(self) -> str:
            model = Model(self.lst_model)
            # Charger le fichier audio
            with wave.open(self.audio_file, "rb") as wf:
                # Vérifier que l'audio est au format requis
                self.is_good_format(wf)
                
                # Initialiser le recognizer de Vosk
                rec = KaldiRecognizer(model, wf.getframerate())
                
                # Transcrire l'audio
                transcription = ""
                while True:
                    data = wf.readframes(4000)
                    if len(data) == 0:
                        break
                    if rec.AcceptWaveform(data):
                        result = rec.Result()
                        text = json.loads(result).get("text", "")
                        transcription += text + " "

                # Ajouter le dernier morceau de transcription
                final_result = rec.FinalResult()
                text = json.loads(final_result).get("text", "")
                transcription += text

            self.text = transcription.strip()
            

    def main(audio:str) -> str:
        listner = "autocorrect_pro/vosk-model-small-fr-0.22"
        Listner = Audio_to_Text(audio, listner)
        Listner.audio_to_text()
        return Listner.text

**Comment by nils010485** [comment]
Merci pour ton retour !

La philosophie de l'application consiste à utiliser des API plutôt que des modèles locaux (du moins pour l'instant) pour garantir une compatibilité avec tous les hardwares et une compatibilité multilingue. Tu pourrais ajouter un endpoint API dans le fichier routes qui prend en compte le fichier MP3 et utilise un endpoint OpenAI Whisper (https://platform.openai.com/docs/guides/speech-to-text) avec quelque chose du genre : 

```
from openai import OpenAI
client = OpenAI()

audio_file = open("/path/to/file/speech.mp3", "rb")
transcription = client.audio.transcriptions.create(
  model="whisper-1", 
  file=audio_file, 
  response_format="text"
)
print(transcription.text)
```

Tu récupères le contenu et tu le places dans le "text input" de la page :). Je pense que je peux peut-être ajouter la fonctionnalité, mais je pense que refactoriser le code de la partie web est prioritaire. En tout cas, si tu intègres la fonctionnalité, n'hésite pas à faire une PR ! 

Aussi, si tu veux absolument fonctionner en local, tu peux exposer un endpoint de type OpenAI like pour ton modèle (comme ça, tu garantis une compatibilité générale avec OpenAI et les autres modèles). 

Bonne soirée,

**Comment by EliottJVN** [comment]
Okay, je vois. Je regarde ça quand j'ai le temps 😉😉

**Comment by nils010485** [comment]
Bonsoir @EliottJVN !  
Je travaillais sur l'application ce soir pour ajouter le support des modèles d'IA locaux (seulement pour la correction de texte), j'en ai profité pour intégrer l'API Whisper d'OpenAI pour la retranscription de texte. 

Si tu as téléchargé l'application depuis le site web, la mise à jour prendra effet au prochain démarrage de l'application ; dans le cas contraire, je te laisse faire un git pull !  Avec cette fonctionnalité, tu peux facilement extraire et retravailler le texte des fichiers audio. Prends note que l'API d'OpenAI est parfois capricieuse, donc n'hésite pas à essayer plusieurs formats. 

J'espère que cela répondra bien à ton besoin 😃. Si tu veux faire des changements ou améliorer la fonctionnalité, n'hésite pas à proposer une PR.

Commit: f0fcb2988e327e887cab67824c574ad4c73781a5
Nils,

**Comment by EliottJVN** [comment]
Okay je regarde tout ça ce weekend.
